(function(_ds){var window=this;var dS=function(a){return!a.classList.contains("material-icons")},lS=async function(a,b){await DevsiteApp.whenReady();const c=_ds.F();var d=DevsiteApp.getInsecureHost();b=b.ea;if(b.origin===c.origin||!d||b.origin===d){try{var e=(0,_ds.um)(b.data)}catch(g){return}d=_ds.Cf(e,1);if(4===d)eS(a,b);else{var f=e.getName();if(f&&(f=a.querySelector(`devsite-iframe iframe[name="${f}"]`)))switch(d){case 5:fS(e,f);break;case 8:gS(b,e,c);break;case 1:hS(b,e,c);break;case 6:case 7:iS(d,c,e);break;case 9:jS(a,e);
break;case 10:kS(e,c)}}}},pS=function(a){a.v=a.querySelector(".devsite-article-body");a.v&&(mS(a),a.C=[]);a.h&&a.h.disconnect();a.j.clear();nS(a);if(!document.body.hasAttribute("appearance")){var b=[...a.querySelectorAll("picture > source.devsite-dark-theme")];for(var c of b){b=c.closest("picture");const d=b.querySelector("img");b.querySelectorAll("source:not(.devsite-dark-theme)").length?c.remove():b&&d&&b.replaceWith(d)}}c=Array.from(a.querySelectorAll(".devsite-nav-title, .devsite-page-title, td > code, th > code"));
"docs"===document.body.getAttribute("layout")&&a.v&&(b=Array.from(a.v.querySelectorAll("h1, h2, h3, h4, h5, h6")),c.push(...b));a.j.clear();a.j=new Set(c);if(_ds.F().hash){c=new _ds.oH;for(const d of a.j)_ds.nH(c,d,dS)}else oS(a,a.j);a.dispatchEvent(new CustomEvent("devsite-content-updated",{bubbles:!0}))},nS=function(a){Array.from(a.getElementsByTagName("table")).forEach(b=>{if(!b.parentNode.classList.contains("devsite-table-wrapper")){var c=document.createElement("div");c.classList.add("devsite-table-wrapper");
b.classList.contains("full-width")&&(c.classList.add("devsite-full-width-table"),b.classList.remove("full-width"));_ds.Ji(c,b);c.appendChild(b)}})},eS=async function(a,b){const c=qS(a,b.source);if(c){const e="goog_"+_ds.qi++;c.setAttribute("name",e);var d=_ds.sm(3);d=_ds.nc(d,2,e);(b=b.source)&&b.postMessage(_ds.Ff(d),"*");(b=document.body.getAttribute("appearance"))&&rS(c,b);a.C.push(c)}},fS=async function(a,b){const c=_ds.Ci(document).y,d=_ds.wf(a,4);a=_ds.wf(a,3);b=_ds.Ri(b);d&&b.setAttribute("width",
`${d}px`);a&&b.setAttribute("height",`${a}px`);window.requestAnimationFrame(()=>{window.scrollTo(_ds.Ci(document).x,c)})},gS=async function(a,b,c){b=_ds.tm(_ds.sm(8),_ds.y(b,8));c=_ds.nc(b,6,c.toString());(a=a.source)&&a.postMessage(_ds.Ff(c),"*")},hS=async function(a,b,c){b=_ds.tm(_ds.sm(2),_ds.y(b,8));c=_ds.nc(b,7,`${c.search}${c.hash}`);(a=a.source)&&a.postMessage(_ds.Ff(c),"*")},iS=async function(a,b,c){const d=c.getTitle();b=new URL(c.getUrl(),b.origin);b=`${window.location.origin}${window.location.pathname}${b.search}${b.hash}`;
6===a?window.history.pushState({},d,b):window.history.replaceState({},d,b)},jS=async function(a,b){const c=_ds.y(b,9);let d;try{d=JSON.parse(_ds.y(b,10))}catch(e){console.warn("Event data from Framebox is not valid JSON.",a);return}"analyticsEvent"===c?a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:d,bubbles:!0})):"cloudtrackEvent"===c?a.dispatchEvent(new CustomEvent("devsite-analytics-observation-cloudtrack",{detail:{eventData:d},bubbles:!0})):"devsite-apix"===c&&a.dispatchEvent(new CustomEvent("devsite-apix-observation",
{detail:d,bubbles:!0}))},kS=async function(a,b){if(a=a.getUrl()){const c=new URL(a,b.origin);a.startsWith("#")||b.origin===c.origin&&b.pathname===c.pathname&&b.search===c.search?DevsiteApp.scrollToAnchor(c.hash,!0):DevsiteApp.fetchPage(c.href)}},qS=function(a,b){let c;Array.from(a.querySelectorAll("devsite-iframe iframe")).forEach(d=>{_ds.Si(d)===b&&(c=d)});return c},rS=function(a,b){var c=_ds.sm(12);b=_ds.nc(c,12,b);a&&a.contentWindow&&(a=a.contentWindow)&&a.postMessage(_ds.Ff(b),"*")},mS=function(a){"full"===
document.body.getAttribute("layout")&&(a=a.v.querySelectorAll('h1[tabindex="0"],h2[tabindex="0"],h3[tabindex="0"],h4[tabindex="0"],h5[tabindex="0"],h6[tabindex="0"]'))&&Array.from(a).forEach(b=>{b.removeAttribute("tabindex")})},oS=function(a,b){a.h&&b.forEach(c=>{a.h.observe(c)})},sS=class extends _ds.E{constructor(){super();this.D=new _ds.G;this.F=new _ds.G;this.j=new Set;this.C=[];this.h=null;"IntersectionObserver"in window&&(this.h=new IntersectionObserver(a=>{for(const b of a)b.isIntersecting&&
(a=b.target,_ds.nH(new _ds.oH,a,dS),this.j.delete(a),this.h.unobserve(a))},{rootMargin:"100%"}))}connectedCallback(){this.D.listen(window,"message",a=>lS(this,a));this.D.listen(document.body,"devsite-appearance-updated",a=>{if((a=a.ea.detail.preference)&&this.C.length)for(const b of this.C)rS(b,a)});pS(this)}disconnectedCallback(){this.h&&this.h.disconnect();this.j.clear();_ds.H(this.D);_ds.H(this.F)}ub(a){a&&([".devsite-article",".devsite-content-data","devsite-content-footer","devsite-notification"].forEach(b=>
{_ds.Mh(this,this.querySelector(b),a.querySelector(b))}),pS(this))}};sS.prototype.updateContent=sS.prototype.ub;sS.prototype.disconnectedCallback=sS.prototype.disconnectedCallback;sS.prototype.connectedCallback=sS.prototype.connectedCallback;try{window.customElements.define("devsite-content",sS)}catch(a){console.warn("devsite.app.customElement.DevsiteContent",a)};})(_ds_www);
